### ISSUE TITLE
Update Node.js verison with the end of Node.js 10 support

### ISSUE THREAD

**Issue by dyson-yamashita** [fossamagna/amplify-category-console-notification#10]
**Is your feature request related to a problem? Please describe.**
Due to the end of Node.js 10 support in AWS Lambda on July 30, 2021, I request a Node.js version of the CloudFormation template for Lambda.
https://docs.aws.amazon.com/ja_jp/lambda/latest/dg/runtime-support-policy.html

**Describe the solution you'd like**
Node.js version up in lambda cloudformation template.

**Comment by fossamagna** [comment]
I published new version 0.3.0.

**Comment by dyson-yamashita** [comment]
Thanks for the merge!
